#!/usr/bin/env python3
"""Generate a hierarchical sample tree for holofs end-to-end testing.

Output layout under `samples/`:

    photos/
      landscapes/   — synthesised gradient "scenes" (mountain, sea, forest, sky)
      abstract/     — mandala-like patterns, gradients, noise, pixel art
      brand-pairs/  — pairs of "logo" + a watermarked/recoloured variant of it,
                      so /similar's robust-copy column produces real hits
    audio/
      music/        — single-tone WAVs (bass/mid/treble) + a layered mix
      effects/      — short SFX (beep, click)
      silence/      — known-zero audio (handy for /health energy bands)
    docs/
      notes/        — small plain-text notes + a markdown TODO
      spec/         — JSON config + a long-ish API draft
      legal/        — copy of an MIT-style licence
    binaries/
      archives/     — zip / tar / tar.gz containing the docs above
      blobs/        — pseudo-binary fixtures (PCG-generated bytes)

All output is deterministic — re-running this script produces byte-identical
files. The PNG / WAV writers are hand-rolled (no external deps) so the
script works on the bare CPython that ships with macOS / most Linux distros.

Usage:

    python3 tools/test-data/generate-samples.py            # → ./samples/
    python3 tools/test-data/generate-samples.py --out /tmp/holofs-samples
"""

from __future__ import annotations

import argparse
import json
import math
import os
import struct
import sys
import tarfile
import zipfile
import zlib
from dataclasses import dataclass
from pathlib import Path

# ---------------------------------------------------------------------------
# Deterministic-but-decent PNG / WAV writers.  Hand-rolled to keep this
# script dependency-free (no PIL, no soundfile).
# ---------------------------------------------------------------------------


def write_png(path: Path, pixels: list[list[tuple[int, int, int]]]) -> None:
    h = len(pixels)
    w = len(pixels[0])
    hdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)
    raw = bytearray()
    for row in pixels:
        raw.append(0)  # filter byte
        for r, g, b in row:
            raw.append(r & 0xFF)
            raw.append(g & 0xFF)
            raw.append(b & 0xFF)
    idat = zlib.compress(bytes(raw), 9)

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", hdr)
        + chunk(b"IDAT", idat)
        + chunk(b"IEND", b"")
    )


def write_wav(path: Path, samples: list[float], sample_rate: int = 44100) -> None:
    # 16-bit PCM mono.
    n = len(samples)
    pcm = bytearray()
    for s in samples:
        v = int(max(-1.0, min(1.0, s)) * 32767)
        pcm.extend(struct.pack("<h", v))
    chunk_size = 36 + len(pcm)
    header = (
        b"RIFF"
        + struct.pack("<I", chunk_size)
        + b"WAVE"
        + b"fmt "
        + struct.pack("<IHHIIHH", 16, 1, 1, sample_rate, sample_rate * 2, 2, 16)
        + b"data"
        + struct.pack("<I", len(pcm))
    )
    path.write_bytes(header + bytes(pcm))


# ---------------------------------------------------------------------------
# Cheap deterministic PRNG (LCG).  Same seed → same output bytes.  Avoids
# pulling random.Random's Mersenne Twister so a parallel Rust / Go port of
# this generator could match byte-for-byte if anyone ever wants that.
# ---------------------------------------------------------------------------


class LCG:
    def __init__(self, seed: int = 0xC0FFEE) -> None:
        self.state = seed & 0xFFFFFFFF

    def next_u32(self) -> int:
        # Numerical Recipes constants — fine for fixtures, not for crypto.
        self.state = (self.state * 1664525 + 1013904223) & 0xFFFFFFFF
        return self.state

    def byte(self) -> int:
        return self.next_u32() & 0xFF

    def f01(self) -> float:
        return self.next_u32() / 0xFFFFFFFF


# ---------------------------------------------------------------------------
# Photo generators.
# ---------------------------------------------------------------------------


def make_landscape(seed: int, name: str, w: int = 256, h: int = 256) -> list[list[tuple[int, int, int]]]:
    """Smooth vertical gradient + horizon line — looks vaguely sceneic and
    has enough low-frequency energy for the /health detail-score block to
    say something meaningful."""
    rng = LCG(seed)
    sky_top = (rng.byte() // 2, rng.byte() // 2 + 64, 200 + rng.byte() // 4)
    sky_bot = (200 + rng.byte() // 4, 220, 240)
    ground_top = (rng.byte() // 2 + 40, 120 + rng.byte() // 3, 50)
    ground_bot = (60 + rng.byte() // 3, 90 + rng.byte() // 3, 30)
    horizon = h // 2 + (rng.next_u32() % 30 - 15)
    px = []
    for y in range(h):
        if y < horizon:
            t = y / max(horizon - 1, 1)
            row = []
            for x in range(w):
                noise = (rng.byte() % 7) - 3
                r = int(sky_top[0] * (1 - t) + sky_bot[0] * t) + noise
                g = int(sky_top[1] * (1 - t) + sky_bot[1] * t) + noise
                b = int(sky_top[2] * (1 - t) + sky_bot[2] * t) + noise
                row.append((r, g, b))
        else:
            t = (y - horizon) / max(h - horizon - 1, 1)
            row = []
            for x in range(w):
                noise = (rng.byte() % 11) - 5
                r = int(ground_top[0] * (1 - t) + ground_bot[0] * t) + noise
                g = int(ground_top[1] * (1 - t) + ground_bot[1] * t) + noise
                b = int(ground_top[2] * (1 - t) + ground_bot[2] * t) + noise
                row.append((r, g, b))
        px.append(row)
    return px


def make_mandala(seed: int, w: int = 256, h: int = 256) -> list[list[tuple[int, int, int]]]:
    """Radial cosine pattern — heavy high-frequency content, useful for
    energy-distribution / texture-band tests."""
    rng = LCG(seed)
    arms = 4 + rng.next_u32() % 8
    cx, cy = w / 2, h / 2
    palette = [(rng.byte(), rng.byte(), rng.byte()) for _ in range(5)]
    px = []
    for y in range(h):
        row = []
        for x in range(w):
            dx, dy = x - cx, y - cy
            theta = math.atan2(dy, dx)
            r = math.hypot(dx, dy) / max(cx, cy)
            v = math.cos(arms * theta) * math.cos(r * 12.0)
            idx = int(((v + 1) / 2) * (len(palette) - 1))
            row.append(palette[idx])
        px.append(row)
    return px


def make_gradient(seed: int, w: int = 256, h: int = 256) -> list[list[tuple[int, int, int]]]:
    rng = LCG(seed)
    c1 = (rng.byte(), rng.byte(), rng.byte())
    c2 = (rng.byte(), rng.byte(), rng.byte())
    diagonal = bool(rng.next_u32() & 1)
    px = []
    for y in range(h):
        row = []
        for x in range(w):
            t = ((x + y) / (w + h)) if diagonal else (x / w)
            r = int(c1[0] * (1 - t) + c2[0] * t)
            g = int(c1[1] * (1 - t) + c2[1] * t)
            b = int(c1[2] * (1 - t) + c2[2] * t)
            row.append((r, g, b))
        px.append(row)
    return px


def make_noise(seed: int, w: int = 256, h: int = 256) -> list[list[tuple[int, int, int]]]:
    rng = LCG(seed)
    return [[(rng.byte(), rng.byte(), rng.byte()) for _ in range(w)] for _ in range(h)]


def make_pixel_art(seed: int, w: int = 256, h: int = 256) -> list[list[tuple[int, int, int]]]:
    rng = LCG(seed)
    palette = [(rng.byte(), rng.byte(), rng.byte()) for _ in range(6)]
    block = 16
    grid = [[palette[rng.next_u32() % len(palette)] for _ in range(w // block)] for _ in range(h // block)]
    px = []
    for y in range(h):
        row = []
        for x in range(w):
            row.append(grid[y // block][x // block])
        px.append(row)
    return px


def make_brand_logo(seed: int) -> list[list[tuple[int, int, int]]]:
    """Solid-colour rectangle on a contrasting background — looks like a
    placeholder brand glyph.  Variants then watermark it."""
    rng = LCG(seed)
    bg = (240 + rng.byte() % 15, 240 + rng.byte() % 15, 240 + rng.byte() % 15)
    fg = (rng.byte(), rng.byte(), rng.byte())
    w = h = 256
    cx, cy = w // 2, h // 2
    r = 80
    px = [[bg for _ in range(w)] for _ in range(h)]
    for y in range(h):
        for x in range(w):
            if (x - cx) ** 2 + (y - cy) ** 2 < r * r:
                px[y][x] = fg
    return px


def make_brand_watermark(base: list[list[tuple[int, int, int]]], seed: int) -> list[list[tuple[int, int, int]]]:
    """Re-render the brand glyph with: 1) a small 'WM' stamp painted into
    the corner (high-freq perturbation), 2) every pixel nudged by a tiny
    per-pixel delta.  /similar's robust-copy column should flag the
    result as "structure matches, detail differs"."""
    rng = LCG(seed + 17)
    h = len(base)
    w = len(base[0])
    out = [row[:] for row in base]
    # Per-pixel nudge.
    for y in range(h):
        for x in range(w):
            r, g, b = out[y][x]
            delta = rng.byte() % 6 - 3
            out[y][x] = (max(0, min(255, r + delta)), max(0, min(255, g + delta)), max(0, min(255, b + delta)))
    # Crude "WM" stamp in the bottom-right.
    for sy in range(8):
        for sx in range(16):
            x, y = w - 24 + sx, h - 16 + sy
            out[y][x] = (255 - out[y][x][0], 255 - out[y][x][1], 255 - out[y][x][2])
    return out


# ---------------------------------------------------------------------------
# Audio generators.
# ---------------------------------------------------------------------------


def tone(freq_hz: float, duration_s: float = 1.5, sample_rate: int = 44100, amplitude: float = 0.4) -> list[float]:
    n = int(duration_s * sample_rate)
    return [amplitude * math.sin(2 * math.pi * freq_hz * i / sample_rate) for i in range(n)]


def silence(duration_s: float = 1.5, sample_rate: int = 44100) -> list[float]:
    return [0.0] * int(duration_s * sample_rate)


def mix(*tracks: list[float]) -> list[float]:
    n = max(len(t) for t in tracks)
    out = [0.0] * n
    for t in tracks:
        for i, v in enumerate(t):
            out[i] += v
    norm = max(abs(v) for v in out) or 1.0
    return [v / norm * 0.8 for v in out]


def beep() -> list[float]:
    # A short two-tone beep.
    return tone(1000.0, 0.08) + silence(0.04) + tone(1500.0, 0.08)


# ---------------------------------------------------------------------------
# Document fixtures.
# ---------------------------------------------------------------------------


NOTE_TXT = """\
holofs test note
================

Reminders for the next session:

* run the GC, see the per-node breakdown
* version a known image twice, then restore the original
* search for "mountain" with band=coarse vs band=full
"""

TODO_MD = """\
# TODO

- [x] Generate sample tree
- [ ] Stage 15.1 — per-block encoding with block_size
- [ ] Reactive-context warnings cleanup
- [ ] Scheduled GC + epoch-based safety window
"""

JOURNAL_TXT = """\
Day 1 — bootstrap, seed the catalog with the synthetic sample tree.
Day 2 — verify /search returns coarse + full hits for the landscapes folder.
Day 3 — PUT a logo, then a watermarked variant; confirm robust-copy fires.
Day 4 — exercise versions: PUT v1, restore v1 after PUT v2, GC.
"""

API_DRAFT_TXT = """\
holofs API draft

GET /              tree-view of the catalog
GET /<name>        full-resolution decode
GET /preview/<name> coarse-layer preview (≈8% of bytes for image/audio)
GET /preview/stream/<name>   multipart streaming hologram
GET /api/spotlight.png       ROI composite (?mode=spatial|coeff)
GET /api/search    semantic search over CLIP embeddings (?band=)
POST /api/gc       orphan-shard sweep
POST /api/restore  versioning round-trip helper
"""

SCHEMA_JSON = json.dumps(
    {
        "object": "holofs-fixture",
        "version": 1,
        "fields": [
            {"name": "name", "type": "string"},
            {"name": "kind", "type": "enum", "values": ["image", "audio", "text", "opaque"]},
            {"name": "size_bytes", "type": "u64"},
            {"name": "tags", "type": "array<string>"},
        ],
    },
    indent=2,
) + "\n"

LICENCE_TXT = """\
MIT-style placeholder licence — for test fixtures only.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
"""


# ---------------------------------------------------------------------------
# Spec
# ---------------------------------------------------------------------------


@dataclass
class Sample:
    rel_path: str
    bytes_: bytes


def collect_samples(out_root: Path) -> list[Sample]:
    """Return every (relative path, bytes) we want to write under
    `out_root`."""
    samples: list[Sample] = []
    write_under = out_root

    # 1. Photos.
    photo_specs = [
        ("landscapes/mountain.png", make_landscape(1, "mountain")),
        ("landscapes/ocean.png", make_landscape(2, "ocean")),
        ("landscapes/forest.png", make_landscape(3, "forest")),
        ("landscapes/desert.png", make_landscape(4, "desert")),
        ("landscapes/tundra.png", make_landscape(5, "tundra")),
        ("abstract/mandala-a.png", make_mandala(11)),
        ("abstract/mandala-b.png", make_mandala(12)),
        ("abstract/gradient-warm.png", make_gradient(21)),
        ("abstract/gradient-cool.png", make_gradient(22)),
        ("abstract/noise-rgb.png", make_noise(31)),
        ("abstract/pixel-blocks.png", make_pixel_art(41)),
    ]
    # Brand pairs: logo + watermarked variant.
    for i in range(3):
        base = make_brand_logo(50 + i)
        photo_specs.append((f"brand-pairs/logo-{i + 1}.png", base))
        photo_specs.append((f"brand-pairs/logo-{i + 1}-wm.png", make_brand_watermark(base, 50 + i)))

    for rel, px in photo_specs:
        target = write_under / "photos" / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        write_png(target, px)
        samples.append(Sample(f"photos/{rel}", target.read_bytes()))

    # 2. Audio.
    audio_specs = [
        ("music/bass.wav", tone(110.0, 2.0)),
        ("music/mid.wav", tone(660.0, 2.0)),
        ("music/treble.wav", tone(3500.0, 2.0)),
        ("music/mixed.wav", mix(tone(110.0, 2.0), tone(660.0, 2.0), tone(3500.0, 2.0))),
        ("music/chord-major.wav", mix(tone(440.0, 2.0), tone(554.0, 2.0), tone(660.0, 2.0))),
        ("music/chord-minor.wav", mix(tone(440.0, 2.0), tone(523.0, 2.0), tone(660.0, 2.0))),
        ("effects/beep.wav", beep()),
        ("effects/double-beep.wav", beep() + silence(0.1) + beep()),
        ("silence/silence-short.wav", silence(1.0)),
        ("silence/silence-long.wav", silence(3.0)),
    ]
    for rel, sig in audio_specs:
        target = write_under / "audio" / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        write_wav(target, sig)
        samples.append(Sample(f"audio/{rel}", target.read_bytes()))

    # 3. Docs.
    doc_specs = [
        ("notes/note.txt", NOTE_TXT.encode("utf-8")),
        ("notes/todo.md", TODO_MD.encode("utf-8")),
        ("notes/journal.txt", JOURNAL_TXT.encode("utf-8")),
        ("spec/api-draft.txt", API_DRAFT_TXT.encode("utf-8")),
        ("spec/schema.json", SCHEMA_JSON.encode("utf-8")),
        ("legal/licence.txt", LICENCE_TXT.encode("utf-8")),
    ]
    for rel, raw in doc_specs:
        target = write_under / "docs" / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(raw)
        samples.append(Sample(f"docs/{rel}", raw))

    # 4. Binaries — pack some of the docs into archives + raw fixture blobs.
    archives_dir = write_under / "binaries" / "archives"
    archives_dir.mkdir(parents=True, exist_ok=True)
    zip_target = archives_dir / "docs.zip"
    with zipfile.ZipFile(zip_target, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("note.txt", NOTE_TXT)
        zf.writestr("todo.md", TODO_MD)
        zf.writestr("api-draft.txt", API_DRAFT_TXT)
    samples.append(Sample("binaries/archives/docs.zip", zip_target.read_bytes()))

    tar_target = archives_dir / "docs.tar"
    # Deterministic-ish tar: drop mtime by setting it to 0 on every member.
    with tarfile.open(tar_target, "w") as tf:
        for name, content in (
            ("note.txt", NOTE_TXT.encode("utf-8")),
            ("schema.json", SCHEMA_JSON.encode("utf-8")),
            ("licence.txt", LICENCE_TXT.encode("utf-8")),
        ):
            info = tarfile.TarInfo(name=name)
            info.size = len(content)
            info.mtime = 0
            tf.addfile(info, fileobj=_BytesReader(content))
    samples.append(Sample("binaries/archives/docs.tar", tar_target.read_bytes()))

    blobs_dir = write_under / "binaries" / "blobs"
    blobs_dir.mkdir(parents=True, exist_ok=True)
    for name, seed, size in (("fixture-small.bin", 71, 1024), ("fixture-medium.bin", 73, 16 * 1024), ("fixture-large.bin", 79, 128 * 1024)):
        target = blobs_dir / name
        rng = LCG(seed)
        target.write_bytes(bytes(rng.byte() for _ in range(size)))
        samples.append(Sample(f"binaries/blobs/{name}", target.read_bytes()))

    return samples


class _BytesReader:
    """Tiny io.BytesIO-compatible wrapper so tarfile.addfile can stream
    deterministically without us depending on io.BytesIO's quirks."""

    def __init__(self, data: bytes) -> None:
        self._buf = data
        self._pos = 0

    def read(self, n: int = -1) -> bytes:
        if n < 0:
            chunk = self._buf[self._pos :]
            self._pos = len(self._buf)
            return chunk
        chunk = self._buf[self._pos : self._pos + n]
        self._pos += len(chunk)
        return chunk


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--out",
        default=os.path.join(os.path.dirname(__file__), "..", "..", "samples"),
        help="output directory (default: <repo>/samples/)",
    )
    args = ap.parse_args()
    out_root = Path(args.out).resolve()
    if out_root.exists():
        # Wipe the previous run so we never serve stale bytes.
        import shutil

        shutil.rmtree(out_root)
    out_root.mkdir(parents=True)
    samples = collect_samples(out_root)
    # Manifest for the upload script — relative path + size.
    manifest_path = out_root / "MANIFEST.txt"
    with manifest_path.open("w") as f:
        for s in samples:
            f.write(f"{len(s.bytes_):>10}  {s.rel_path}\n")
    total = sum(len(s.bytes_) for s in samples)
    print(f"wrote {len(samples)} samples ({total:,} bytes) under {out_root}")
    print(f"manifest at {manifest_path.relative_to(out_root.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
